In [3]:
import  numpy as np
import pickle
import pandas as pd

In [50]:
with open("onehot_encoder.pkl", 'rb') as f:
    onehot_encoder = pickle.load(f)

In [51]:
with open("label_encoder.pkl", "rb") as f:
    label_encoder = pickle.load(f)

In [52]:
with open("pca_model.pkl", "rb") as f:
    pca = pickle.load(f)

In [53]:
with open("Car_price_mode.pkl", "rb") as f:
    model = pickle.load(f)

#### user_input

In [73]:
import pandas as pd

data = {
    'symboling': 3,
    'fueltype': ['gas'],
    'aspiration': 'std',
    'doornumber': 'two',
    'carbody': 'convertible',
    'drivewheel': 'rwd',
    'enginelocation': 'front',
    'wheelbase': 88.6,
    'carlength': 168.8,
    'carwidth': 64.1,
    'carheight': 48.8,
    'curbweight': 2548,
    'enginetype': 'dohc',
    'cylindernumber': 'four',
    'enginesize': 130,
    'fuelsystem': 'mpfi',
    'boreratio': 3.47,
    'stroke': 2.68,
    'compressionratio': 9,
    'horsepower': 111,
    'peakrpm': 5000,
    'citympg': 21,
    'highwaympg': 27
}

df_user = pd.DataFrame(data, index = [0])
df_user

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,four,130,mpfi,3.47,2.68,9,111,5000,21,27

### applying one hot encoding

In [63]:
one_hot_cols = ['carbody', 'drivewheel', 'enginetype', 'cylindernumber', 'fuelsystem']
df_encoded = pd.DataFrame(onehot_encoder.transform(df[one_hot_cols]).toarray(), columns=onehot_encoder.get_feature_names_out(one_hot_cols))
df =  pd.concat([df, df_encoded], axis=1)
df = df.drop(one_hot_cols, axis=1)
df

,symboling,fueltype,aspiration,doornumber,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,...,cylindernumber_twelve,cylindernumber_two,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,3,gas,std,two,front,88.6,168.8,64.1,48.8,2548,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

### applying label encoding

In [65]:
label_cols = ['fueltype', 'aspiration', 'doornumber', 'enginelocation']
for col in label_cols:
    label_encoder.fit(df[col])
    df[col] = label_encoder.transform(df[col])
df

,symboling,fueltype,aspiration,doornumber,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,...,cylindernumber_twelve,cylindernumber_two,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,3,0,0,0,0,88.6,168.8,64.1,48.8,2548,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

### apply pca

In [67]:
df_pca_array = pca.transform(df)
pca_columns = [f"PC{i}" for i in range(1, pca.n_components_ + 1)]
df_pca_array = pd.DataFrame(df_pca_array, columns=pca_columns)
df_pca_array

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,...,PC19,PC20,PC21,PC22,PC23,PC24,PC25,PC26,PC27,PC28
0,73.624153,-90.694833,10.659046,6.155582,5.73883,-8.742292,5.373764,5.061742,-0.847861,0.688332,...,-0.466066,-0.612435,0.294868,-0.537196,0.219887,0.753105,0.72626,0.366969,0.235489,0.329733

### test the model

In [70]:
predicted_price = model.predict(df_pca_array)[0]
predicted_price

12712.786396396361

In [74]:
class CarPriceModel():
    def load_label_encoder(self, label_file_path):
        with open(label_file_path, 'rb') as f:
            label_encoder = pickle.load(f)
        return label_encoder

    def load_onehot_encoder(self, onehot_file_path):
        with open(onehot_file_path, 'rb') as f:
            onehot_encoder = pickle.load(f)
        return onehot_encoder
    
    def load_pca_model(self, pca_file_path):
        with open(pca_file_path, 'rb') as f:
            pca_model = pickle.load(f)
        return pca_model
    
    def load_model(self, model_file_path):
        with open(model_file_path, 'rb') as f:
            model = pickle.load(f)
        return model
    
    def preprocess_data(self, df, onehot_encoder, label_encoder):
        # Apply one-hot encoding
        one_hot_cols = ['carbody', 'drivewheel', 'enginetype', 'cylindernumber', 'fuelsystem']
        df_encoded = pd.DataFrame(onehot_encoder.transform(df[one_hot_cols]).toarray(), columns=onehot_encoder.get_feature_names_out(one_hot_cols))
        df =  pd.concat([df, df_encoded], axis=1)
        df = df.drop(one_hot_cols, axis=1)
        
        # Apply label encoding
        label_cols = ['fueltype', 'aspiration', 'doornumber', 'enginelocation']
        for col in label_cols:
            label_encoder.fit(df[col])
            df[col] = label_encoder.transform(df[col])
        return df
    
    def apply_pca(self, df, pca_model):
        df_pca_array = pca_model.transform(df)
        pca_columns = [f"PC{i}" for i in range(1, pca_model.n_components_ + 1)]
        df_pca_array = pd.DataFrame(df_pca_array, columns=pca_columns)
        return df_pca_array
    
    def predict_price(self, model, df_pca_array):
        predicted_price = model.predict(df_pca_array)[0]
        return predicted_price

In [75]:
car_price_prediction = CarPriceModel()
price = car_price_prediction.predict_price(df_user)
price

TypeError: CarPriceModel.predict_price() missing 1 required positional argument: 'df_pca_array'

In [76]:
class CarPriceModel():
    def __init__(self, label_file_path, onehot_file_path, pca_file_path, model_file_path):
        self.label_encoder = self.load_label_encoder(label_file_path)
        self.onehot_encoder = self.load_onehot_encoder(onehot_file_path)
        self.pca_model = self.load_pca_model(pca_file_path)
        self.model = self.load_model(model_file_path)

    def load_label_encoder(self, label_file_path):
        with open(label_file_path, 'rb') as f:
            label_encoder = pickle.load(f)
        return label_encoder

    def load_onehot_encoder(self, onehot_file_path):
        with open(onehot_file_path, 'rb') as f:
            onehot_encoder = pickle.load(f)
        return onehot_encoder
    
    def load_pca_model(self, pca_file_path):
        with open(pca_file_path, 'rb') as f:
            pca_model = pickle.load(f)
        return pca_model
    
    def load_model(self, model_file_path):
        with open(model_file_path, 'rb') as f:
            model = pickle.load(f)
        return model
    
    def preprocess_data(self, df):
        # Apply one-hot encoding
        one_hot_cols = ['carbody', 'drivewheel', 'enginetype', 'cylindernumber', 'fuelsystem']
        df_encoded = pd.DataFrame(self.onehot_encoder.transform(df[one_hot_cols]).toarray(), columns=self.onehot_encoder.get_feature_names_out(one_hot_cols))
        df = pd.concat([df, df_encoded], axis=1)
        df = df.drop(one_hot_cols, axis=1)
        
        # Apply label encoding
        label_cols = ['fueltype', 'aspiration', 'doornumber', 'enginelocation']
        for col in label_cols:
            df[col] = self.label_encoder.transform(df[col])
        return df
    
    def apply_pca(self, df):
        df_pca_array = self.pca_model.transform(df)
        pca_columns = [f"PC{i}" for i in range(1, self.pca_model.n_components_ + 1)]
        df_pca_array = pd.DataFrame(df_pca_array, columns=pca_columns)
        return df_pca_array
    
    def predict_price(self, df):
        # Preprocess data
        df_preprocessed = self.preprocess_data(df)

        # Apply PCA
        df_pca_array = self.apply_pca(df_preprocessed)

        # Make prediction
        predicted_price = self.model.predict(df_pca_array)[0]
        return predicted_price

In [77]:
car_price_prediction = CarPriceModel()
price = car_price_prediction.predict_price(df_user)
price

TypeError: CarPriceModel.__init__() missing 4 required positional arguments: 'label_file_path', 'onehot_file_path', 'pca_file_path', and 'model_file_path'